# Site
repository: chan8616/chan8616.github.io 
# Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/jin.ico
# Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Chanyang Seo
title: AI Engineer
email: cksdid0209@gmail.com
# email_title: Email (Email title override)
# phone: 
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false
use_math: true

# Social links
#twitter_username: jekyllrb
github_username:  chan8616
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: chanyang-seo-038670244
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/chan.jpg
# Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I'm interested in artificial intelligence and algorithms.
  For my recent research area, I've been working on [Voronoi diagram](https://en.wikipedia.org/wiki/Voronoi_diagram#:~:text=In%20mathematics%2C%20a%20Voronoi%20diagram,%2C%20sites%2C%20or%20generators) 
  and shortest paths under the $L_1$ metric.
  
  I have experience with <mark>pytorch</mark> <mark>SQL</mark> and <mark>Ipe</mark>(Geometric objects drawing tool).
content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        border: weak
        title: POSTECH
        sub_title: Master of Science in Artificial Intelligence
        caption: 2020-2022
        quote: >
          Title of Thesis: Shortest Paths Between Line Segments in the Presence of Rectangular obstacles 
      - layout: top-right
        title: Inha University
        sub_title: Bachelor of in International Trade
        caption: 2010-2015
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        sub_title: Shortest Paths Between Line Segments in the Presence of Rectangular Obstacles
        link: Link to project
        link_text: Korea Computer Congress 2022
        quote: >
          [Abstract] In this paper, we present an algorithm to compute $L_1$ shortest paths between two vertical or horizontal line segments avoiding $n$ axis-aligned rectangular obstacles.
          The suggested algorithm computes the minimum shortest path in $O(n \log n)$ time using $O(n)$ space and the maximum shortest path in $O(n^2)$ time and $O(n^2)$ space.
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        sub_title: Farthest-point Voronoi diagrams in the presence of rectangular obstacles
        link: https://drops.dagstuhl.de/opus/volltexte/2022/16059/pdf/LIPIcs-SoCG-2022-51.pdf
        link_text: the 38th International Symposium on Computational Geometry (SoCG 2022)
        quote: >
          [Abstract] We present an algorithm to compute the geodesic $L_1$ farthest-point Voronoi diagram of $m$ point sites 
          in the presence of $n$ rectangular obstacles in the plane. It takes $O(nm + n \log n + m \log m)$ construction time using $O(nm)$ space.
          This is the first optimal algorithm for constructing the farthest-point Voronoi diagram in the presence of rectangular obstacles. 
          We can construct a data structure in the same construction time and space that answer a farthest-neighbor query in $O(\log(n+m)) time.
      - layout: top-left
        sub_title: Design and Implementation of Word Classes Embedding for Improving FastText
        link: https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE07503217
        link_text: Korea Computer Congress 2018
        quote: >
          [Abstract] Compared to English or other foreign languages, 
          Korean has many types of conjugation due to the nature of the language. 
          Depending on the word embedding technique, 
          there is a clear difference in the performance of the NLP model. 
          Therefore, in this paper, we propose WCE (Word Classes Embedding), 
          a new word embedding technique that supplements fastText to be suitable for learning Korean sentence structure. 
          WCE is an improved method for better learning part-of-speech information 
          by adding part-of-speech information of words to the fastText-based embedding dimension.
          Text generation results using WCE show more complete sentence structure than FastText alone.
  - title: Awards
    layout: list
    content:
      - layout: right
        title: Best Paper Award(Computer Theory)
        sub_title: Korea Computer Congress 2022
        caption: Shortest Paths Between Line Segments in the Presence of Rectangular Obstacles
        link: https://www.kiise.or.kr/conference/board/boardview.do?CC=kcc&CS=2022&PARENT_ID=050100&&NUM=317
      - layout: right
        title: Scholarship for academic excellence
        sub_title: Inha University
        caption: 2010, 2011
  - title: Experience
    layout: list
    content:
      - layout: right
        border: weak
        title: POSTECH Institute of Artificial Intelligence
        sub_title: AI Researcher
        caption: 2018-2022
        link: http://piai.postech.ac.kr
        description: | # this will include new lines to allow paragraphs
          Developing AI softwares 
          - Object detection
          - Image segmentation
          - Anomaly Detection
      - layout: right
        title: H.FOR
        sub_title: Database developer
        caption: 2016-2018
        link: http://www.hfor.net/
        description: | # this will include new lines to allow paragraphs
          Developing Database Search System 
          - PL/SQL
          - SQL
          - ORACLE
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In addition to my research interests, here's a list of my favorites:
      - My lovely puppies, **Jinseok** and **Jingook**
      
      ![jj](/images/j_bros.jpg)
      - Traveling
      - Knitting

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
