# Site
repository: chan8616/chan8616.github.io 
# Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/jin.ico
# Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Chanyang Seo
title: AI Engineer
email: cksdid0209@gmail.com
# email_title: Email (Email title override)
# phone: 
# phone_title: Phone (Phone title override)
website: https://peng-hi.tistory.com
website_title: Blog
portfolio: https://www.notion.so/chanyangseo/Chanyang-s-Portfolio-7a7ec506213543eba57ab78e140a7d94
portfolio_title: Portfolio

# Dark Mode (true/false/never)
darkmode: false
use_math: true

# Social links
github_username:  chan8616
linkedin_username: chanyang-seo-038670244

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/chan.jpg
# Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I'm interested in artificial intelligence and algorithms.
  Recently, I've been working on [Voronoi diagram](https://en.wikipedia.org/wiki/Voronoi_diagram#:~:text=In%20mathematics%2C%20a%20Voronoi%20diagram,%2C%20sites%2C%20or%20generators) 
  and shortest paths under the $L_1$ metric.
  
  I have experience with <mark>pytorch</mark> <mark>SQL</mark> and <mark>Ipe</mark>(Geometric objects drawing tool).
content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        border: weak
        title: POSTECH
        sub_title: Master of Science in Artificial Intelligence
        caption: 2020-2022
        quote: >
          Title of Thesis: Shortest Paths Between Line Segments in the Presence of Rectangular obstacles 
      - layout: top-right
        title: Inha University
        sub_title: Bachelor of Science in Business Administration and Economics (International Trade)
        caption: 2010-2015
        quote: >
          Dean’s list (2010 - 2013)
  - title: Study Abroad
    layout: list
    content:
      - layout: right
        border: weak
        title: Carnegie Mellon University
        sub_title: IITP program
        caption: 2022.01-2022.07
        description: | # this will include new lines to allow paragraphs
          Courses:
          - 11-785 Introduction to Deep Learning
          - 11-775 Large-scale Multimedia Analysis
          - 17-745 Machine Learning in Production
          - 17-737 Artificial Intelligence for Social Good
      - layout: right
        border: weak  
        title: University of Rhode Island
        sub_title: Exchange Student
        caption: 2013.09-2014.02
        description: |
          Courses:
          - Intro. to Astronomy: Solar system
          - Introduction to Resource Econ
          - Prin of Econ: Macroeconomics
          - Intermediate Chinese 1
      - layout: right
        title: Tianjin University
        caption: 2011
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  
        title: Shortest Paths Between Line Segments in the Presence of Rectangular Obstacles
        sub_title: Chanyang Seo, Taehoon Ahn, Hee-Kap Ahn
        link: Link to project
        link_text: Korea Computer Congress 2022
        quote: >
          [Abstract] In this paper, we present an algorithm to compute $L_1$ shortest paths between two vertical or horizontal line segments avoiding $n$ axis-aligned rectangular obstacles.
          The suggested algorithm computes the minimum shortest path in $O(n \log n)$ time using $O(n)$ space and the maximum shortest path in $O(n^2)$ time and $O(n^2)$ space.
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Farthest-point Voronoi diagrams in the presence of rectangular obstacles
        sub_title: Mincheol Kim, Chanyang Seo, Taehoon Ahn, Hee-Kap Ahn
        link: https://drops.dagstuhl.de/opus/volltexte/2022/16059/pdf/LIPIcs-SoCG-2022-51.pdf
        link_text: the 38th International Symposium on Computational Geometry (SoCG 2022)
        quote: >
          [Abstract] We present an algorithm to compute the geodesic $L_1$ farthest-point Voronoi diagram of $m$ point sites 
          in the presence of $n$ rectangular obstacles in the plane. It takes $O(nm + n \log n + m \log m)$ construction time using $O(nm)$ space.
          This is the first optimal algorithm for constructing the farthest-point Voronoi diagram in the presence of rectangular obstacles. 
          We can construct a data structure in the same construction time and space that answer a farthest-neighbor query in $O(\log(n+m)) time.
      - layout: top-middle
        title: Design and Implementation of Word Classes Embedding for Improving FastText
        sub_title: Hyungbae Cho, Chanyang Seo, Soyoung Kang, Eunyoung Youn
        link: https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE07503217
        link_text: Korea Computer Congress 2018
        quote: >
          [Abstract] Compared to English, 
          Korean has many types of conjugation due to the nature of the language. 
          Depending on the word embedding technique, 
          there is a clear difference in the performance of the NLP model. 
          Therefore, in this paper, we propose WCE (Word Classes Embedding), 
          a new word embedding technique that supplements fastText to be suitable for learning Korean sentence structure. 
          WCE is an improved method for better learning part-of-speech information 
          by adding part-of-speech information of words to the fastText-based embedding dimension.
  - title: Research Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        border: weak  
        title: AI Based Optimal Operation Path Search
        link: https://www.skhynix.com/
        link_text: by SK Hynix
        caption: 2020.12. - 2021.09.
        description: | # this will include new lines to allow paragraphs
          Task:
          - Design Deep Neural Networks(RNNs, GNNs) to find the optimal paths
          - Data Preprocessing for Reinforcement Learning
      - layout: top-left
        border: weak  
        title: Fault Detection of Gas Pressure Regulator
        link: https://www.kogas.or.kr/
        link_text: by KOGAS
        caption: 2018.12. - 2020.07.
        description: | # this will include new lines to allow paragraphs
          Task:
          - Data Preprocessing
          - Design Deep Neural Networks(RNNs, GNNs) to detect failure of gas pressure regulator
          - Applying boosting algorithms to detect failure of gas pressure regulator
      - layout: top-left
        border: weak  
        title: Developing a GUI tool to train Deep Neural Network
        link: https://github.com/chan8616/PoAI
        link_text: by PIAI
        caption: 2018.05. - 2020.08.
        description: | # this will include new lines to allow paragraphs
          Task:
          - Design and develop GUI tool for the process of training DNN models
          - Implement Deep learning models inside the tool
      - layout: top-left
        title: AI for writing Korean Poetry
        link: http://pirl.postech.ac.kr/news/view/id/79#u
        link_text: by PIAI
        caption: 2018.01. - 2018.04.
        description: | # this will include new lines to allow paragraphs
          Task:
          - Preprocessing of Korean poetry
          - Design and train Seq2Seq model to generate Korean poetry
  - title: Working Experiences
    layout: list
    content:
      - layout: right
        border: weak
        title: POSTECH Institute of Artificial Intelligence
        sub_title: AI Researcher
        caption: 2018-2022
        link: http://piai.postech.ac.kr
        description: | # this will include new lines to allow paragraphs
          Developing AI softwares 
          - Object detection
          - Image segmentation
          - Anomaly Detection
      - layout: right
        title: H.FOR
        sub_title: Database developer
        caption: 2016-2018
        link: http://www.hfor.net/
        description: | # this will include new lines to allow paragraphs
          Developing Database Search System 
          - PL/SQL
          - SQL
          - ORACLE
  - title: Educational Activities
    layout: list
    content:
      - layout: right
        border: weak
        title: Teaching Assistant
        sub_title: CSED331 Algorithms, POSTECH
        caption: 2021
        description: | # this will include new lines to allow paragraphs
          Algorithms
          - Divide and conquer
          - Graph algorithms
          - Greedy algorithm
          - Dynamic programming
          - Heuristic algorithms
      - layout: right
        border: weak
        title: Teaching Assistant
        sub_title: POSCO AI Expert
        caption: 2021
        description: | # this will include new lines to allow paragraphs
          Algorithms
          - Divide and conquer
          - Graph algorithms
          - Greedy algorithm
          - Dynamic programming
          - Heuristic algorithms
      - layout: right
        border: weak
        title: Teaching Assistant
        sub_title: Hustar Innovation Academy
        caption: 2019
        description: | # this will include new lines to allow paragraphs
          Computer vision
          - Semantic segmentation
          - Object segmentation
      - layout: right
        title: Teaching Assistant
        sub_title: Hustar Innovation Academy
        caption: 2019
        description: | # this will include new lines to allow paragraphs
          Computer vision
          - Semantic segmentation
          - Object segmentation
  - title: Language Skills
    layout: list
    content:
      - layout: right
        border: weak
        title: Korean
        sub_title: Mother tongue
      - layout: right
        border: weak
        title: English
        sub_title: Communicative in oral and written
        caption: TOEIC 940
      - layout: right
        title: Chinese
        sub_title: Communicative in oral and written
        caption: HSK Level5 250
  - title: Honors and Awards
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Best Paper Award
        sub_title: Shortest Paths Between Line Segments in the Presence of Rectangular Obstacles
        #caption: Shortest Paths Between Line Segments in the Presence of Rectangular Obstacles
        link: https://www.kiise.or.kr/conference/board/boardview.do?CC=kcc&CS=2022&PARENT_ID=050100&&NUM=317
        link_text: Korea Computer Congress 2022
      - layout: top-middle
        title: Scholarship for academic excellence
        sub_title: Inha University
        caption: 2010, 2011
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In addition to my research interests, here's a list of my favorites:
      - My lovely puppies, **Jinseok** and **Jingook**
      
      ![jj](/images/j_bros.jpg)
      - Traveling
      - Knitting

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
